name: Bump version and update image.tag

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allows creating and pushing tags 
  packages: read
  pull-requests: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Install yq
        run: |
          ls -la
          sudo apt-get update && sudo apt-get install -y jq
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: 1172473
          private-key: ${{ secrets.CI_CD_SECRET }}
          owner: adalat-ai-ci-cd-org
          repositories: ci-cd-charts-test

      - name: Debug Token Access
        run: |
          echo "Checking token permissions..."
          curl -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/user"

      - name: Check Token Scope
        run: |
          curl -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/installation/repositories"

      - name: Checkout Second Repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: adalat-ai-ci-cd-org/ci-cd-charts-test
          ref: alpha  # Specify the branch if needed

      - name: Update image.tag in values.yaml
        run: |
          echo "Current directory: $(pwd)"
          ls -la ci-cd-test
          NEW_TAG=${{ steps.tag_version.outputs.new_tag }}
          echo "Updating image.tag to ${NEW_TAG}"
          yq eval -i ".image.tag = \"${NEW_TAG}\"" ci-cd-test/values.yaml
          cat ci-cd-test/values.yaml  # for debugging

      # - name: Commit and Push Changes
      #   run: |
      #     git config user.name "github-actions"
      #     git config user.email "github-actions@github.com"

      #     git add ci-cd-test/values.yaml
      #     git commit -m "Updated image.tag to ${{ steps.tag_version.outputs.new_tag }}" || echo "No changes to commit"
      #     git push origin alpha
      #   env:
      #     GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "Updated image.tag to ${{ steps.tag_version.outputs.new_tag }}"
          branch: "update-image-tag"
          base: "alpha"
          title: "chore: update image.tag to ${{ steps.tag_version.outputs.new_tag }}"
          body: "This PR updates `image.tag` to `${{ steps.tag_version.outputs.new_tag }}` automatically."

      - name: Debug PR Creation
        run: |
          echo "Pull Request Number: ${{ steps.create-pull-request.outputs.pull-request-number }}"

      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pull-request: ${{ steps.create-pull-request.outputs.pull-request-number }}
          merge-method: squash  # Options: merge, squash, rebase