name: Bump version and update image.tag

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allows creating and pushing tags 
  packages: read
  pull-requests: write 

jobs:
  semver-tagging:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: "Automated release for ${{ steps.tag_version.outputs.new_tag }}."

  update-charts-repo:
    runs-on: ubuntu-latest
    needs: semver-tagging
    strategy:
      matrix: 
        service:
          - { name: "document-service", paths: "^internal/document", values_path: "ci-cd-test/values.yaml" }
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Check if relevant files were changed
        id: check_changes
        run: |
          CHANGED_FILES="$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"
          echo "Changed files: $CHANGED_FILES"
          
          run_update="false"

          while IFS= read -r path; do
            echo "Checking path: $path"
            if echo "$CHANGED_FILES" | grep -q "$path"; then
              echo "Changes detected in $path"
              run_update="true"
            fi
          done <<< "$(echo "${{ matrix.service.paths }}" | tr ' ' '\n')"

          echo "run_update=$run_update" >> $GITHUB_ENV

      - name: Exit if no relevant changes
        if: env.run_update == 'false'
        run: echo "No changes in ${{ matrix.service.paths }}, skipping update."

      - name: Install yq
        run: |
          ls -la
          sudo apt-get update && sudo apt-get install -y jq
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: 1172473
          private-key: ${{ secrets.CI_CD_SECRET }}
          owner: adalat-ai-ci-cd-org
          repositories: ci-cd-charts-test

      - name: Checkout Second Repo
        if: env.run_update == 'true'
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: adalat-ai-ci-cd-org/ci-cd-charts-test
          ref: alpha 

      - name: Update image.tag in values.yaml
        if: env.run_update == 'true'
        run: |
          echo "Current directory: $(pwd)"
          NEW_TAG=${{ needs.semver-tagging.outputs.new_tag }}
          echo "Updating ${{ matrix.service.values_path }} image.tag to ${NEW_TAG}"
          yq eval -i ".image.tag = \"${NEW_TAG}\"" ${{ matrix.service.values_path }}
          cat ${{ matrix.service.values_path }}  # for debugging

      - name: Create Pull Request
        if: env.run_update == 'true'
        id: create-pr 
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "Updated ${{ matrix.service.name }} image.tag to ${{ needs.semver-tagging.outputs.new_tag }}"
          branch: "update-${{ matrix.service.name }}-image-tag-${{ needs.semver-tagging.outputs.new_tag }}" 
          base: alpha
          title: "chore: [${{ matrix.service.name }}] update image.tag to ${{ needs.semver-tagging.outputs.new_tag }}"
          body: "This PR updates `image.tag` in `${{ matrix.service.values_path }}` to `${{ needs.semver-tagging.outputs.new_tag }}` automatically."

      - name: Enable Auto-Merge
        if: env.run_update == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: adalat-ai-ci-cd-org/ci-cd-charts-test 
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash  